general.import = [
   #"~/.config/alacritty/catppuccin-frappe.toml"
   #"~/.config/alacritty/rose-pine.toml"
   #"~/.config/alacritty/gruvbox.toml"
   #"~/.config/alacritty/ashen.toml"
   "~/.config/alacritty/kanagawa-dragon.toml"
]

[env]
TERM = "xterm-256color"

[window]
#padding = { x = 3, y = 3 }
#dynamic_padding = true
opacity = 0.9

[window.padding]
x = 0
y = 0

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0

[font.glyph_offset]
x = 0
y = 0


